// Generated by CoffeeScript 1.10.0
var NamedFunction, Stack, flattenStack, isConstructor, repeatString, setType;

isConstructor = require("isConstructor");

NamedFunction = require("named-function");

repeatString = require("repeat-string");

flattenStack = require("flattenStack");

setType = require("setType");

module.exports = Stack = NamedFunction("Stack", function(array) {
  return setType({
    array: array
  }, Stack);
});

Stack.prototype.push = function(stack) {
  return this.array.push(stack);
};

Stack.prototype.flatten = function() {
  return Stack.flatten(this.array);
};

Stack.prototype.print = function() {
  return console.log(Stack.format(this.flatten()));
};

Stack.flatten = flattenStack;

Stack.format = function(stack) {
  var locations, longestMethodName;
  longestMethodName = 0;
  locations = stack.map(function(frame) {
    if (!isConstructor(frame, Object)) {
      return;
    }
    if (frame.methodName == null) {
      frame.methodName = "[anonymous]";
    }
    if (longestMethodName < frame.methodName.length) {
      longestMethodName = frame.methodName.length;
    }
    return frame.file + ":" + frame.lineNumber + ":" + frame.column;
  });
  return stack.map(function(frame, index) {
    var whitespace;
    if (!isConstructor(frame, Object)) {
      return frame;
    }
    whitespace = repeatString(" ", 2 + longestMethodName - frame.methodName.length);
    return frame.methodName + whitespace + locations[index];
  }).join("\n");
};
